os: Visual Studio 2013

shallow_clone: true
clone_depth: 1

platform: x64

cache:
  - x86_64-4.9.2-release-posix-seh-rt_v4-rev2.7z

install:
  - cinst wget
  - wget --no-clobber "http://sourceforge.net/projects/mingw-w64/files/Toolchains targetting Win64/Personal Builds/mingw-builds/4.9.2/threads-posix/seh/x86_64-4.9.2-release-posix-seh-rt_v4-rev2.7z"
  - 7z x -oC:\MinGW\msys\1.0\ x86_64-4.9.2-release-posix-seh-rt_v4-rev2.7z > nul

build_script:
  - C:\MinGW\msys\1.0\bin\sh.exe -c "cd /c/projects/Sunsetter/; /c/projects/Sunsetter/msys_build.sh"

artifacts:
  - path: sunsetter-windows-*

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'lichess.org custom Sunsetter binaries'
  skip_cleanup: true
  provider: GitHub
  auth_token:
    secure: 6etg+ncawYNJCoADtQWuYC5GE/m4TUJrfag1nX1Q2fk2jLaicdt2GeE1kUWDm+gu
  artifact: /sunsetter-windows-.*/
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
